version: '3.7'

services: 
    mongo:
        container_name: mongo-microservices
        image: mongo:latest
        restart: always
        ports: 
            - 27017:27017        
        volumes: 
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    
    rabbitmq:
      image: rabbitmq:3-management
      restart: always
      container_name: 'rabbitmq-microservices'
      ports:
          - 5672:5672
          - 15672:15672
